/* Important Modules */

#include "legacy\Core\generalfunc.pwn"
#include "legacy\Core\area.pwn"
#include "legacy\Core\streamer.pwn"
#include "legacy\Core\animations.pwn"
#include "legacy\Core\economy.pwn"
#include "legacy\Core\veh_core.pwn"
#include "legacy\Core\streamer-comp.pwn"
/* Faction Modules */
#include "legacy\Faction\DynamicFaction.pwn"
#include "legacy\Faction\General.pwn"
#include "legacy\Faction\Medic.pwn"
#include "legacy\Faction\Police.pwn"
#include "legacy\Faction\Government.pwn"
#include "legacy\Faction\News.pwn"

/* VIP */
#include "legacy\Core\vip.pwn"

/* Server Feature Modules */
#include "legacy\Feature\Toys.pwn"
#include "legacy\Feature\911call.pwn"
#include "legacy\Feature\Phone.pwn"
#include "legacy\Feature\TruckerCargo.pwn"
#include "legacy\Feature\SprayTag.pwn"
#include "legacy\Feature\Report.pwn"
#include "legacy\Feature\Business.pwn"
#include "legacy\Feature\FuelPump.pwn"
#include "legacy\Feature\DynamicActor.pwn"
#include "legacy\Feature\DynamicVehicle.pwn"
#include "legacy\Feature\FactionGarage.pwn"
#include "legacy\Feature\Dealership.pwn"
#include "legacy\Feature\Rental.pwn"
#include "legacy\Feature\Furniture.pwn"
#include "legacy\Feature\House.pwn"
#include "legacy\Feature\PublicGarage.pwn"
#include "legacy\Feature\Flat.pwn"
#include "legacy\Feature\Warning.pwn"
#include "legacy\Feature\Gate.pwn"
#include "legacy\Feature\Inventory.pwn"
#include "legacy\Feature\LumberTree.pwn"
#include "legacy\Feature\Dropitem.pwn"
#include "legacy\Feature\Ticket.pwn"
#include "legacy\Feature\Weed.pwn"
#include "legacy\Feature\ATM.pwn"
#include "legacy\Feature\WeaponAttachment.pwn"
#include "legacy\Feature\Speedcam.pwn"
#include "legacy\Feature\DMV.pwn"
#include "legacy\Feature\AFK.pwn"
#include "legacy\Feature\Injured.pwn"
#include "legacy\Feature\Salary.pwn"
#include "legacy\Feature\Mask.pwn"
#include "legacy\Feature\Advertisement.pwn"
#include "legacy\Feature\Insurance.pwn"
#include "legacy\Feature\Interior.pwn"
#include "legacy\Feature\Door.pwn "
#include "legacy\Feature\SAM.pwn"
#include "legacy\Feature\MOTD.pwn"
#include "legacy\Feature\Workshop.pwn"
#include "legacy\Feature\DynamicDoor.pwn"
#include "legacy\Feature\GPS.pwn"
#include "legacy\Feature\MappingInGame.pwn"
#include "legacy\Feature\Boombox.pwn"
#include "legacy\Feature\Family.pwn" 
#include "legacy\Feature\AntiCheat.pwn" 
#include "legacy\Feature\Accent.pwn" 
#include "legacy\Feature\Spike.pwn"
#include "legacy\Feature\AntiTapping.pwn"
#include "legacy\Feature\AntiBikeHop.pwn"
#include "legacy\Feature\VehicleKeys.pwn"
#include "legacy\Feature\Racing.pwn"
#include "legacy\Feature\Rock.pwn"
#include "legacy\Feature\Speedlimit.pwn"
// #include "legacy\Feature\Speedupgrade.pwn"
#include "legacy\Feature\Roadblock.pwn"
#include "legacy\Feature\Quiz.pwn"
#include "legacy\Feature\Damage.pwn"
#include "legacy\Feature\Navigator.pwn"
#include "legacy\Feature\Gunrack.pwn"
#include "legacy\Feature\Tax.pwn"
#include "legacy\Feature\Blackmarket.pwn"
#include "legacy\Feature\Marriage.pwn"
#include "legacy\Feature\WatchTV.pwn"
#include "legacy\Feature\FactionVault.pwn"
#include "legacy\Feature\Vote.pwn"
#include "legacy\Feature\FlyMode.pwn"

/* Job Modules */
#include "legacy\Job\Smuggler.pwn"
#include "legacy\Job\Trucker.pwn"
#include "legacy\Job\General.pwn"
#include "legacy\Job\Fishing.pwn"
#include "legacy\Job\Sweeper.pwn"
#include "legacy\Job\Lumberjack.pwn"
#include "legacy\Job\Bus.pwn"
#include "legacy\Job\Vendor.pwn"
#include "legacy\Job\Mechanic.pwn"
#include "legacy\Job\Taxi.pwn"
#include "legacy\Job\Butcher.pwn"
#include "legacy\Job\Trashmaster.pwn"
#include "legacy\Job\Mower.pwn"
#include "legacy\Job\DeliveryDriver.pwn"
#include "legacy\Job\Miner.pwn"
#include "legacy\Job\Hauling.pwn"

/* Other Important Modules */
#include "legacy\Core\player.pwn"
#include "legacy\Core\generalcmd_player.pwn"
#include "legacy\Core\generalcmd_admin.pwn"
#include "legacy\Core\mapping.pwn"
#include "legacy\Core\serverstuff.pwn"

/* Raknet */

#include "legacy\Core\pawnraknet.pwn"